---

- name: Initialize variable
  set_fact:
    logstash_combined_config: {}

- name: Create environment variable to carry the logstash keystore password
  set_fact:
    _logstash_keystore_environment:
      LOGSTASH_KEYSTORE_PASS: "{{ logstash_keystore_password }}"
  when: logstash_keystore_password != None
