---

- name: Check if a keystore exists
  stat:
    path: /etc/logstash/logstash.keystore
  register: result

- name: Create logstash keystore
  command: >-
    bin/logstash-keystore create
      --path.settings /etc/logstash
  args:
    chdir: /usr/share/logstash
  when: not result.stat.exists | bool
  environment: "{{ _logstash_keystore_environment | default({}) }}"
