---

- name: Create pipeline configuration directories
  file:
    path: >-
      {{
        (
          logstash_pipelines
          | selectattr('pipeline.id', 'equalto', item.0.id)
          | list
        )[0]['path']['config']
        | default(
          logstash_combined_config['path']['config']
          | default('/etc/logstash/conf.d/')
          + '/*.conf'
        )
        | dirname
      }}/
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0o0750
  loop: "{{ logstash_pipeline_configs | subelements('files', skip_missing=true) }}"
  notify: logstash restart service

- name: Upload pipeline configuration files
  template:
    src: "{{ item.1 }}"
    dest: >-
      {{
        (
          logstash_pipelines
          | selectattr('pipeline.id', 'equalto', item.0.id)
          | list
        )[0]['path']['config']
        | default(
          logstash_combined_config['path']['config']
          | default('/etc/logstash/conf.d/')
          + '/*.conf'
        )
        | dirname
      }}/
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0o0640
  loop: "{{ logstash_pipeline_configs | subelements('files', skip_missing=true) }}"
  notify: logstash restart service

- name: Upload inline pipeline configs
  copy:
    content: "{{ item.content }}"
    dest: "{{ logstash_pipelines[0].path.config | dirname }}/{{ item.id }}.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0o0640
  loop: "{{ logstash_pipeline_configs }}"
  when: item.content is defined
  notify: logstash restart service
