---

- name: Get user/pass variables
  set_fact:
    _logstash_userpass_variables: >-
      {{
        q(
          'varnames',
          '^logstash_config_.*_(user|username|pass|password|passphrase)$'
        )
      }}

- block:
    - name: Remove existing keystore record
      command: >-
        bin/logstash-keystore remove '{{ item }}'
          --path.settings /etc/logstash
      args:
        chdir: /usr/share/logstash
      register: result
      failed_when:
        - result is failed
        - result.stderr is not search('does not exist in the Logstash keystore')
      when: logstash_keystore_update | bool
      loop: "{{ _logstash_userpass_variables }}"

    - name: List keystore settings
      command: bin/logstash-keystore list --path.settings /etc/logstash
      args:
        chdir: /usr/share/logstash
      register: _logstash_keystore_existing_entries
      changed_when: false

    - name: Add passwords and passphrases to logstash keystore
      shell: |
        set -o pipefail;
        echo '{{ lookup('vars', item) }}' |
        bin/logstash-keystore add \
          '{{ item }}' --stdin --path.settings /etc/logstash
      args:
        chdir: /usr/share/logstash
        executable: /bin/bash
      when:
        - lookup('vars', item) | d('__undefined__', true) != '__undefined__'
        - _logstash_keystore_existing_entries.stdout is not search(item)
      loop: "{{ _logstash_userpass_variables }}"
      notify: logstash restart service
      # no_log: true
  environment: "{{ _logstash_keystore_environment | default({}) }}"
